distributable:
  url: https://github.com/bkneis/lazyaws/releases/download/v{{version}}/lazyaws_{{version}}_{{platform.os}}_{{platform.arch}}.tar.gz
  strip-components: 0

versions:
  github: bkneis/lazyaws/releases/tags
  strip: /^v/

provides:
  - bin/lazyaws

test: lazyaws --version
